name: Penney and Logan
favicon: null
layout_spectrum: 0.23179
typography_spectrum: 0.67665
title: Penney and Logan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#e4190b'
    - '#fe7524'
    - '#fdfdfd'
    - '#ecc300'
  brandStrength: 0.6683727074414492
  lightness: 0.11455592582933605
  saturation: 0.3170220341999084
  rhythmicContrast: 0.8763046113308519
purpose: []
